### ISSUE TITLE
Scallion/cathugger attack on Tor

### ISSUE THREAD

**Issue by githubisstalkingme** [cathugger/mkp224o#1]
@cathugger
https://trac.torproject.org/projects/tor/ticket/23969

**Comment by cathugger** [comment]
this tool is just bruteforcing keys.
generating full key via bruteforce would take too much resources, at best I can bruteforce first 6 characters on my laptop, which is 30 bits. and for that I need to wait quite a bit.
full public key is 256 bits. that's 226 bits more. every bit multiplies complexity by 2.
so I'd need 2^226 ~= 1.0784×10⁶⁸ such laptops to bruteforce one key. I don't think one can really call that attack.
