### ISSUE TITLE
What is validity of this domain .onion 

### ISSUE THREAD

**Issue by nityam2007** [cathugger/mkp224o#105]
What is validity of this domain .onion 

like i use ./mkp224o nsheth -v -n 10 -d ~/domain -t 4

and i got 10 domain 

set workdir: /home/n/domain/
sorting filters... done.
filters:
        nsheth
in total, 1 filter
using 4 threads
nshethaxxx.onion
waiting for threads to finish... done.

and i want to know what is it validity 
like time year or month or day or time  

can you help me with this as if it got changed during production then it will be damaging for me and my client i.e. is my friends

**Comment by brig371** [comment]
it is forever yours, as long as you keep private key in secret

**Comment by nityam2007** [comment]
> it is forever yours, as long as you keep private key in secret

thanks for reply

**Comment by nityam2007** [comment]
get the answer
