### ISSUE TITLE
Hostname + Public Key + Secret Key only 223 bytes!

### ISSUE THREAD

**Issue by redrosa** [cathugger/mkp224o#18]
I run as follows:
./mkp224o -t 1 test
and naturally I get some testjr20t9fw.onion

However when I go into the folder as root, the hostname, public_key, and private_key are only 223 bytes! Perhaps this is how it is supposed to be, but it seems extremely small to me. Is this normal?

**Comment by cathugger** [comment]
```
$ wc -c *
 63 hostname
 64 hs_ed25519_public_key
 96 hs_ed25519_secret_key
223 total
```
public key is 32 bytes + 32 bytes header.
secret key is 64 bytes + 32 bytes header.
hostname is 62 characters + newline.
so yeah looks legit to me.
ed25519 keys are pretty small compared to RSA.
<https://ed25519.cr.yp.to> lists that as one of features.
