### ISSUE TITLE
Come up with a friendlier name 

### ISSUE THREAD

**Issue by bmintz** [cathugger/mkp224o#2]
shallot, scallion, and even horse25519 are more memorable names than "make proposal 224 onion".

Please come up with a friendlier name. Suggestions: conch or seashell

**Comment by cathugger** [comment]
Personally, I find mkp224o to be perfectly memorable, and `mk` prefix pretty intuitive..
Quick github search of "seashell" brought quite much results, and I don't want name clashes.
Same with "conch".
And they also don't seem to have clear association with onions shallot and scallion have.
Someone else complained about this too, with suggestion of onionater, which is pretty OK for project name tbh though I'd still like to keep mkp224o as tool name.
What you think about this?

**Comment by bmintz** [comment]
Hmm I guess I see what you mean about seashell and conch not being related to onions. But "seashell tor" returns no results, and "conch tor" returns just 1 unrelated one. Considering I found shallot by searching for "shallot tor" on DuckDuckGo, I think one of those could work. Honestly I had no idea shallots and scallions were onions though lol. In that case we could go with like "walla walla",  "triploid", "diploid", or "leek".

I'm not much of a fan of onionater though.

**Comment by cathugger** [comment]
hrm. after thinking about it a bit I don't really think it's a good idea to change it.
It's very unique (try googling it), and already included in ianix.com like that.
At this point it would only cause confusion to give it more generic name.
