### ISSUE TITLE
v1.4.0 Windows

### ISSUE THREAD

**Issue by TemhAAhmeT** [cathugger/mkp224o#26]
Hi,

There is no binary file, mkp224o-w64.zip for version 1.4.0 like previous versions.

**Comment by TemhAAhmeT** [comment]
I have compiled it for linux but have no idea how to combile exe 💃 :D

**Comment by cathugger** [comment]
my windows VM is sorta busted so I've been looking into how to crosscompile it from linux using mingw.
meanwhile, u can use msys2 or cygwin to compile on windows, it should work well.
I should deliver build, eventually.

**Comment by cathugger** [comment]
fyi ive released v0.5.0 with windows bins included, these should work
