### ISSUE TITLE
How can I use this on windows?

### ISSUE THREAD

**Issue by trip1me** [cathugger/mkp224o#30]

**Comment by cathugger** [comment]
download https://github.com/cathugger/mkp224o/releases/tag/v1.3.0
unpack
shift+right click, "Open command window here", type in `mkp224o` (without backquotes), it should print usage instructions.

**Comment by PacoBell** [comment]
A better solution, IMHO, if you use a relatively recent version of Windows 10 is to build mkp224o in Windows Subsystem for Linux (WSL). Works great as a CPU stress test 😂

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by cathugger** [comment]
either way works tbh.
wouldn't call "throw it under compatibility subsystem, even when native builds are available" necessarily better.
installing MSYS2 and compiling with that would be the best, and IMO aint much harder than doing it under WSL.
