### ISSUE TITLE
Crashes if filter file doesn't exist

### ISSUE THREAD

**Issue by jscott0** [cathugger/mkp224o#33]
Doing `./mkp224o -f foo` if foo doesn't exist causes it to segfaut.

    #0  _IO_fgets (buf=0x7fffffffdd60 "", n=128, fp=0x0) at iofgets.c:47
    #1  0x00000000004031b9 in loadfilterfile (fname=0x7fffffffe3fd "seven") at filters_main.inc.h:503
    #2  0x00000000004034c7 in main (argc=0, argv=0x7fffffffe090) at main.c:260

**Comment by cathugger** [comment]
addressed in https://github.com/cathugger/mkp224o/commit/e933a9b806adddac26ac6c167a8c54e9a668efa9

**Comment by cathugger** [comment]
v0.5.0 with fix released.
