### ISSUE TITLE
Filters cannot contain the character 0

### ISSUE THREAD

**Issue by robputt796** [cathugger/mkp224o#34]
Hello,

I have been trying to generate a URL with the number 0 in it, unfortunately, whenever this is used in a filter it fails...

```
filter "test0" is invalid
            ^
```

This happens with any filter with a "0" character, is this a bug or is this intended? Seems a little odd.

Best Regards,

Rob

**Comment by garceri** [comment]
I have the same problem with filters ending in 8, but i was able to generate hosts with the following suffixes
`test1
test2
test3
test4
test5
test6
test7`

Seems like it chokes with 8,9 and 0

**Comment by 00-matt** [comment]
The encoding used by v3 onion addresses (a base32 encoding) doesn't have 1, 8, 9, or 0 in its alphabet to prevent confusion with other similar looking characters (like i, b, or o).

**Comment by robputt796** [comment]
Thanks, that makes sense, I never really used b32 before so assumed it would be like b16 and include 0-9 and letters, anyway, thanks for the clarification. I'll get this issue closed as its not an actual issue.

**Comment by cathugger** [comment]
also https://github.com/cathugger/mkp224o/issues/29

**Comment by cathugger** [comment]
should probably add faq section to readme, apparently it's frequently enough misunderstood that people keep making issues about it
