### ISSUE TITLE
fatal error: sodium/core.h: No such file or directory

### ISSUE THREAD

**Issue by TalusUnheil** [cathugger/mkp224o#35]
Hey there - bloody end-user here ;)

Today I tried to use your tool on my LinuxMint 19.1 machine. Steps to reproduce:
```
cd /tmp/
git clone https://github.com/cathugger/mkp224o.git
cd ./mkp224o
./autogen.sh
./configure
make
```

But after executing the "make" command I got the the following error::
```
gcc -std=c99 -Wall -Wextra -Wno-maybe-uninitialized -Wno-unused-function -Wmissing-prototypes -Wstrict-prototypes -O3 -march=native -fomit-frame-pointer  -DED25519_donna  -DSTATISTICS -c -o main.c.o.tmp main.c && mv main.c.o.tmp main.c.o
main.c:12:10: fatal error: sodium/core.h: No such file or directory
 #include <sodium/core.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
GNUmakefile:130: recipe for target 'main.c.o' failed
make: *** [main.c.o] Error 1
```
There is no "sodium" subfolder in this repository/ folder. What did I miss/ do wrong?

Thx in advance!

**EDIT:**
According to `apt-cache search sodium' the package "libsodium-dev" seems to be a good choice. Alternatively I could install libsodium according to [their instructions](https://doc.libsodium.org/installation). What would would you advise me to do?

**Comment by scribblemaniac** [comment]
As the requirements say in the README.txt, you need to install libsodium. The apt package libsodium-dev should be fine. You usually don't need to compile programs or libraries from source unless they don't have a package (like this repo), you need a specific version other than the one provided by the package, or if you want to develop it.

**Comment by TalusUnheil** [comment]
> As the requirements say in the README.txt, you need to install libsodium.

Those who can read are clearly at an advantage. Thanks for the advice! *feels ashamed*
