### ISSUE TITLE
Error building on OpenBSD

### ISSUE THREAD

**Issue by ndalliard** [cathugger/mkp224o#36]
I try to build `mkp224o` on OpenBSD-current. `libsodium`, `gmake` and `autoconf` are installed.

I am running:

1. `./autogen.sh`
2. `./configure CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"`
3. `gmake`

And get the error `ld: error: unable to find library -lsodium`.

Any ideas what the problem might be?

**Comment by cathugger** [comment]
that's odd I remember testing on some stable OpenBSD version and that worked for me

**Comment by cathugger** [comment]
guess I could install stable version again and check if it works for me.
not gonna bother with -current though.

**Comment by ndalliard** [comment]
I can test it on OpenBSD 6.7. Will report.

**Comment by ndalliard** [comment]
Never mind, I deleted the old repo, cloned a new one and everything worked fine on -current.
No idea what I did wrong the first time...

**Comment by cathugger** [comment]
I suspect you could've ran `./configure` forgetting `CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"` at some point.
New GNUMakefile generated will overwrite old one, thus LDFLAGS stuff doesn't carry over.
Just an idea what could've happened.

**Comment by ndalliard** [comment]
You are the best. That's what probably happened. Pretty sure I ran `./configure` the first time without settings the correct flags. Thank you!
