### ISSUE TITLE
documentation sucks

### ISSUE THREAD

**Issue by cathugger** [cathugger/mkp224o#37]
as reminder for myself to add faq section and at least some actual usage examples.

**Comment by tohn** [comment]
I'd be happy to help you with this task and maybe also to convert the README file to markdown?
If you want I can create a PR for this (convert README + include some examples).

**Comment by cathugger** [comment]
making this into markdown is probably good idea, as I sorta resisted it initially but now that I adjusted spacing a bit to make it less compressed and it still looks kinda odd, plus whole FAQ section...
as for example, I think I included one as first FAQ entry:
```
 * How do I generate address?
 - Once compiled, run it like `./mkp224o neko`, and it will try creating keys
   for onions starting with "neko" in this example; use `./mkp224o -d nekokeys neko` to
   not litter current directory and put all discovered keys in directory named "nekokeys".
```
idk if this is enough but I think it is now.

**Comment by cathugger** [comment]
I think since #41 got merged docs look okay now so I can close this.
