### ISSUE TITLE
OpenCL/CUDA Support?

### ISSUE THREAD

**Issue by Elycin** [cathugger/mkp224o#4]
Awesome job on this repository for something so new, but i'm curious to know if you plan to add extensions for GPU support to accelerate the rate?

I've been running a filter of 9 characters long for a total of 6 hours and still nothing at 303Mh/s 

Would be awesome to see!

**Comment by cathugger** [comment]
I was looking into maybe probably learning OpenCL and adding support for it (https://eprint.iacr.org/2014/198.pdf seem to have some nice tips for that), but I have zero OpenCL experience atm and not much free time to learn... so maybe in future, but I'm not really sure for now.
Pull requests for that are welcome.
Not planning to do CUDA tho as I don't have hardware for it and don't really like their lock-in.

**Comment by Elycin** [comment]
OpenCL is understandable since both cards would support it. 
I wish you the best if you do manage to attempt this!

**Comment by kolet** [comment]
@cathugger  hey there buddy!
any update ?
that would be so great if u did implement such thing for V3..

**Comment by cathugger** [comment]
don't really have proper setup to test on atm.
my Intel Ivy Bridge thing only properly runs beignet OpenCL impl (not release, but git version of it), and it's apparently not really updated anymore and fails to compile with newest LLVM. so maybe I should just close this issue and reopen when I'm actually up for it.

**Comment by cathugger** [comment]
>when
(if ever)
