### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by NetOperatorWibby** [cathugger/mkp224o#43]
When running `make` I get `main.c:12:10: fatal error: 'sodium/core.h' file not found`. My C experience is nil but it looks like I'm missing the `sodium` package on my system.

**Comment by SuperSandro2000** [comment]
Install the sodium package-

**Comment by NetOperatorWibby** [comment]
`brew install libsodium` was what I needed. Thanks!

**Comment by sunknudsen** [comment]
On M1 Mac:

**Step 1:** install [Homebrew](https://brew.sh/)

**Step 2:** install autoconf and libsodium

```shell
brew install autoconf libsodium
```

**Step 3:** clone and compile mkp224o

```shell
git clone https://github.com/cathugger/mkp224o.git
cd mkp224o
./autogen.sh
CPPFLAGS="-I/opt/homebrew/Cellar/libsodium/1.0.18_1/include" LDFLAGS="-L/opt/homebrew/Cellar/libsodium/1.0.18_1/lib" ./configure
make
```

**Comment by txt-file** [comment]
For https://macports.org the proper commands are

install libsodium: `sudo port install libsodium`

clone & compile mkp224o
```
git clone https://github.com/cathugger/mkp224o.git
cd mkp224o
./autogen.sh
CPPFLAGS="-I/opt/local/include/" LDFLAGS="-L/opt/local/lib/" ./configure
make
```
