### ISSUE TITLE
Unable to filter 1 keyword on ARM64 PC

### ISSUE THREAD

**Issue by zhihuiyuze** [cathugger/mkp224o#45]
filter "1" is invalid
        ^
sorting filters... done.
in total, 0 filters
using 2 threads
>calc/sec:5403423.911414, succ/sec:0.000000, rest/sec:19.987807, elapsed:0.100061sec
^Cwaiting for threads to finish... done.
I compiled and installed on an aarch64 host without special options, and then found that the above error occurred. There is no such error when using the precompiled version on Windows

**Comment by cathugger** [comment]
https://github.com/cathugger/mkp224o/issues/29 https://github.com/cathugger/mkp224o/issues/34
also in FAQ

**Comment by cathugger** [comment]
maybe if people read https://github.com/cathugger/mkp224o/commit/f6bda1035c80097adc5b3152eaef4d6ba9890d1e they'll understand?
