### ISSUE TITLE
Build for android?

### ISSUE THREAD

**Issue by remedycoin** [cathugger/mkp224o#47]
Hello,
I'm interested in building this to run on android so it can take advantage of the gpu.  Is this possible?
I've been using an environment called Termux on android for running youtube-dl.

I don't have a computer with a GPU so I figured a phone version might be great.  Perhaps it could be distributed as an Android app?  
Thank you. 
Joe Baker
Founder, ForgivenessCapital.com

**Comment by cathugger** [comment]
it can't take advantage of phone gpus. because it wasn't coded for phone gpus. and i dont think it would make sense anyway as they are probably pretty weak, and i have no idea whether they even have compute-focused apis.
