### ISSUE TITLE
Missing filters when binsearch is enabled and besort is not

### ISSUE THREAD

**Issue by xPMo** [cathugger/mkp224o#49]
Running with `./configure --enable-intfilter=64 --enable-binsearch --enable-amd64-64-24k --enable-batchnum=4096`.

Attempted: `./mkp224o 2 33333 -vd tmp.onion

Output:

```
set workdir: tmp.onion/
sorting filters... removing duplicates... done.
filters:
	2aaaa
	2eaaa
	2iaaa
	2maaa
	2qaaa
	2uaaa
	2yaaa
	24aaa
	2aaab
	2eaab
	2iaab
	2maab
	2qaab
	2uaab
	2yaab
	24aab
	33333
in total, 17 filters
```

Expected: Many more filters.

**Comment by cathugger** [comment]
Yeah seems broken. Nice catch.
For now you can use `--enable-besort` configure flag which should make things faster than default binfilter (but probably still slower than intfilter) and not broken.

**Comment by xPMo** [comment]
I'm just filling out the prefixes manually with a bit of Zsh brace expansion instead.

```zsh
max_length=9
for filter ($(< prefixes.txt)){
    new=($filter[1,max_length])
    repeat max_length-$#filter new=($^new{{a..z},{2..7}})
    list+=($new)
}
print -l $list > fixed-prefixes.txt
```

**Comment by cathugger** [comment]
should be fixed in https://github.com/cathugger/mkp224o/commit/f43c3b021e4ace3c79dcad7a4d290fe06b0126c3.

**Comment by cathugger** [comment]
@xPMo should be fixed as of latest master so try if you wanna. ill probably close this later.

**Comment by xPMo** [comment]
Nice, it seems to work.  Thanks!
