### ISSUE TITLE
unknown type name ‘IFT’

### ISSUE THREAD

**Issue by NinjaGlitch** [cathugger/mkp224o#50]
**Tried to compile on AMD and intel system
Both shows same error** 

gcc -std=c99 -Wall -Wextra -Wno-maybe-uninitialized -Wno-unused-function -Wmissing-prototypes -Wstrict-prototypes -O3 -march=native -fomit-frame-pointer  -DED25519_donna  -DSTATISTICS 
-DPASSPHRASE -c -o main.c.o.tmp main.c && mv main.c.o.tmp main.c.o
In file included from filters_main.inc.h:3,
                 from main.c:181:
ifilter_bitsum.h:3:8: error: unknown type name ‘IFT’
 static IFT ifilter_bitsum(IFT x)
        ^~~
ifilter_bitsum.h:3:27: error: unknown type name ‘IFT’
 static IFT ifilter_bitsum(IFT x)
                           ^~~
make: *** [GNUmakefile:131: main.c.o] Error 1

**Comment by cathugger** [comment]
this was fixed in https://github.com/cathugger/mkp224o/commit/fc6285523f615e31f9d313a667e6ca8a9d781872 but i was too lazy to log into github at that point
