### ISSUE TITLE
Show partial matches

### ISSUE THREAD

**Issue by stefan-reich** [cathugger/mkp224o#52]
That seems like a pretty nice feature to me - always print the longest partial match found. Yes? No?

**Comment by cathugger** [comment]
Additional logic for this will likely degrade performance. I'm thinking that no.

**Comment by cathugger** [comment]
it depends on whether it's using intfilter or default binfilter. with intfilter, it uses integer sized masking and checking operations wholesale, while with binfilter it does byte-by-byte masking and checking.

**Comment by cathugger** [comment]
currently it discards tens of millions of keys if not more for few successful key finds, and adding any sort of "longest partial match" state logic in that path would seriously mess with perf. maybe not in very large way but it definitely would be measurable

**Comment by cathugger** [comment]
so yeah i won't be implementing this.
