### ISSUE TITLE
FEATURE: Add flag to exit after first successful found address

### ISSUE THREAD

**Issue by anthonybudd** [cathugger/mkp224o#55]
I would like to use mkp224o in a project but I just want to generate one address.  Simply flooding a directory with potential onion addresses won't work for my use case.

It would be great if I could pass a flag (`-e`) to the command that will exit after the first successful address is generated. 

**Example**
```
$> ./mkp224o -e -d addresses anthony
set workdir: addresses/
sorting filters... done.
filters:
	anthony
in total, 1 filter
using 4 threads
>calc/sec:17035.009192, succ/sec:1.000000, rest/sec:39.964831, elapsed:0.100088sec
anthonyezawwi5r3o7lrgsno43jj7vq5en74czuw6wfmjzkhjjryxnid.onion
Found matching address exiting....

$> ls /addresses
anthonyezawwi5r3o7lrgsno43jj7vq5en74czuw6wfmjzkhjjryxnid.onion
```

**Comment by Scripter17** [comment]
You can use `-n 1` for this

It's listed in `--help`

**Comment by anthonybudd** [comment]
Thanks
