### ISSUE TITLE
Save and port state of calculation to other machine or just pause and resume on same machine. Is that possible?

### ISSUE THREAD

**Issue by meckli** [cathugger/mkp224o#57]
I'd like to know if there's a possibility to pause a running calculation, save the state to disc and resume later at the same point after rebooting or maybe even on another machine without loosing the work that's already been done. That would be great.

**Comment by cathugger** [comment]
mkp224o does wild guessing, have multiple states (one per thread) and resets them upon successful match.
there is nothing to gain from saving states, wild guessing starting from one random state as opposed to another is still wild guessing.

**Comment by meckli** [comment]
Thanks for your reply. I'm not sure if I understand "wild guessing" right. So does it mean that it is possible that the same address is being tried more than once during the run from no successful match, or from one to the next?

**Comment by politician** [comment]
It is more likely that you will find a 31 characters match than mkp224o trying the same address twice.
And neither of this is going to happen in a billion years with your current machine.

**Comment by meckli** [comment]
thx
