### ISSUE TITLE
Workaround to use without any filter?

### ISSUE THREAD

**Issue by devilnator** [cathugger/mkp224o#64]

**Comment by scribblemaniac** [comment]
Why would you want to? The whole point of this program is to generate vanity onion addresses. There are other, better tools you can use if you just want to generate an ed25519 key pair (ex. OpenSSH). Heck, I'm pretty sure Tor can generate them for you automatically.

If you *really* needed to you could build the program with regex and do a search string like `.`, or even just use the normal search with a filter file contain an entry for every base32 character. But this will start writing keys to your disk as fast as possible until you stop the program or you run out of space. This program is capable of generating millions of keys per second.

**Comment by devilnator** [comment]
I don't want to run it for vanity. I want it to save all the domains generated as it does after filtering, I want it to save each and every domain generated without checking for a specific string.

**Comment by scribblemaniac** [comment]
> I don't want to run it for vanity.

Then this isn't the right program for you.

Anyway I have already provided you with multiple suggested workarounds. Is there anything more you need for this issue to be resolved?

**Comment by cathugger** [comment]
it's possible to do but it's not really worth doing as writing to file system or stdout will be significantly slower than key generation itself on anything viable for this to run
