### ISSUE TITLE
onion v2 and  i2p b32 address generator?

### ISSUE THREAD

**Issue by dimzon** [cathugger/mkp224o#7]
I really like this program usability - it creates different folder for each address, i can supply multiple regex via text file etc, it's really user-friendly!
Is it possible to merge escalion code for V2 addresseses and add I2P b32 address generator too?

**Comment by cathugger** [comment]
Maybe. Would need a bit of refactoring but with current code it wouldn't be too hard.
I was actually planning doing something like this for i2p b32.
Not sure if it's worth supporting old onion addresses though.
This isn't something I'd do quickly, though.
So maybe, if I find enough free time and feel like doing it.

**Comment by cathugger** [comment]
I tried to look into i2p generation, and its ed25519 addresses generation is a bit different than I expected.
b32 is basically sha256sum of https://geti2p.net/spec/common-structures#keysandcert and that'd need me to implement elgamal key generation, and bruteforcing approach is also different (we have 96 bytes of padding if we do ed25519 and we can freely change that, so in essence bruteforcing is just doing fast sha256 with possibly some state reuse).
unsure if worth doing, as it's quite different from how onion v3 generation works.

**Comment by cathugger** [comment]
if I decide to do it, imo it would be more fitting to do it as separate project, possibly reusing some code from this.
having this issue open here is only misleading at this point.

**Comment by xanoni** [comment]
I know that there are generators for this now, any recommendations?

**Comment by cathugger** [comment]
v2 will be dead v soon and for i2p i think they used to have one in i2pd repo i forgot

**Comment by xanoni** [comment]
Yes I was referring to I2P. I've seen a bunch of vanity .b32.i2p's recently, curious what they all use.
