### ISSUE TITLE
Does stopping and restarting lose progress?

### ISSUE THREAD

**Issue by GhislaineDeF** [cathugger/mkp224o#73]
I've been running for about 30 days now, and based on the calculations from #27 I expect the average on my system for the key I'm trying to find to be around 90 days.

It would solve some headaches if I could reboot the server before then. If I stop, reboot and restart the program, is there some sort of progress that I lose or am I equally as likely to find a key as if I hadn't stopped it, losing only progress in the time my server was shut off rather than the full 30 days of trying?

**Comment by scribblemaniac** [comment]
If you ran the program with a passphrase, you will loose your progress by shutting down the program unless you also ran it with checkpointing enabled. If you did not run it with a passphrase, the keys tested are non-deterministic (ie. random), so there is no progress to lose and you can start and stop the program whenever you want. See also my comment here: https://github.com/cathugger/mkp224o/issues/59#issuecomment-944859483

**Comment by GhislaineDeF** [comment]
Thank you for the quick and clear response! That helps me a lot.
