### ISSUE TITLE
filter "test69" is not valid base32 string

### ISSUE THREAD

**Issue by mooleshacat** [cathugger/mkp224o#74]
I am running a test on a machine, using some filters:
./mkp224o -d onions -t 6 test12 test25 test69

but I get errors:
```
filter "test12" is not valid base32 string
            ^
filter "test69" is not valid base32 string
             ^
set workdir: onions/
sorting filters... done.
filters:
        test25
in total, 1 filter
using 6 threads
waiting for threads to finish... done.
```

Am I missing something? Is there a reason that some numbers (25) are allowed while others (12, 69) are not?

**Comment by scribblemaniac** [comment]
From the readme:
> Onion addresses use base32 encoding which does not include 0,1,8,9 numbers.
So no, that's not possible to generate these, and mkp224o tries to detect invalid filters containing them early on.
