### ISSUE TITLE
Is This Character Allowed in A Filter?

### ISSUE THREAD

**Issue by AlexLandherr** [cathugger/mkp224o#77]
I'm new to your program and am wondering whether v3 onion addresses support the `-` character aka "minus sign", "dash" etc?

**Comment by scribblemaniac** [comment]
No. v3 Onion addresses are base32 and support the 26 letters of the latin alphabet, and the numbers 2, 3, 4, 5, 6, and 7.

**Comment by AlexLandherr** [comment]
> No. v3 Onion addresses are base32 and support the 26 letters of the latin alphabet, and the digits 2, 3, 4, 5, 6, and 7.

Ok, thanks for the clarification! I'm in the process of generating a few vanity addresses on a RPi4B (quite short ones obviously). Should be fun.

Thanks again for answering my question.
