### ISSUE TITLE
Question | Windows?

### ISSUE THREAD

**Issue by kolet** [cathugger/mkp224o#8]
hi, is that possible to compile this for Windows OS? 64bit

(if it does is that possible to put a one in the release in github)

cheers

**Comment by cathugger** [comment]
I haven't tried but this maybe could work in cygwin. At the moment it probably won't compile as native windows application, though

**Comment by cathugger** [comment]
also windows 10 has something like linux subsystem for windows, may be worth trying out

**Comment by cathugger** [comment]
actually adding windows support was easier than I expected. it now compiles under msys2

**Comment by cathugger** [comment]
https://github.com/cathugger/mkp224o/releases/tag/V1.0.0
reopen if this doesn't work
