### ISSUE TITLE
Segmentation fault when using regex filters

### ISSUE THREAD

**Issue by FliegendeWurst** [cathugger/mkp224o#9]

**Comment by cathugger** [comment]
seems to be caused by last commit's `pthread_attr_setstacksize(tattrp,20<<10);`. increasing to 80KiB (iirc, musl default) seems to fix at least for simple cases.
sorry for delay, haven't noticed this issue.

**Comment by cathugger** [comment]
fixed in cf4443b7fdbaf8f528e3c4340d4faf2318a19f9d
