### ISSUE TITLE
Compiling with xcode and --enable-amd64-51-30k has invalid .section in consts.S

### ISSUE THREAD

**Issue by safeandeffectivemyass** [cathugger/mkp224o#90]
Hi,

I think that there should be some ifdef for compiling with xcode and ./configure --enable-amd64-51-30k, as it gives:

```
ed25519/amd64-51-30k/consts.S:1:17: error: unexpected token in '.section' directive
.section .rodata

make: *** [ed25519/amd64-51-30k/consts.S.o] Error 1
```

I fixed it on my end with:

```
.text

.global .rodata

.globl CRYPTO_NAMESPACE(batch_REDMASK51)
...
```

Instead of the .section that's there.

Thanks.

**Comment by cathugger** [comment]
have you tried substituting `.section .rodata` with `.const` or `.data` instead?
it seems that it changed when i ported this to new SUPERCOP, at https://github.com/cathugger/mkp224o/commit/f374555fd4d2d8b28bff3e7e98c362073f173038
used to be `.data`, i can't really find whether linux supports this but `.const` seems like it would be MacOS  equivalent to what `.section .rodata` should do on linux.
i guess i could either do conditional compile to use `.const` for macos, or `.data` for all targets.

**Comment by cathugger** [comment]
i don't have a mac to test with

**Comment by safeandeffectivemyass** [comment]
Let me check.

**Comment by safeandeffectivemyass** [comment]
That gives me:

```
ed25519/amd64-51-30k/consts.S:1:8: error: unexpected token in section switching directive
.const .rodata
       ^
make: *** [ed25519/amd64-51-30k/consts.S.o] Error 1
```

Did I get you right on `.const .rodata`?

**Comment by cathugger** [comment]
no, just `.const`, not `.const .rodata`

**Comment by safeandeffectivemyass** [comment]
That works.

**Comment by cathugger** [comment]
could you try replacing it with
```
#ifndef __APPLE__
.section .rodata
#else
.const
#endif
```
and tell if that works

**Comment by safeandeffectivemyass** [comment]
Works well. Thank you.

**Comment by safeandeffectivemyass** [comment]
Guess this should be applied to  amd64-64-24k etc., as well.

**Comment by cathugger** [comment]
yeah.

**Comment by cathugger** [comment]
https://github.com/cathugger/mkp224o/commit/68928c49849170e06f3c1f6c01ef0a12cd2385c2 should probably be good.

**Comment by safeandeffectivemyass** [comment]
I'll re-clone and compile, just for good measure.

**Comment by safeandeffectivemyass** [comment]
Compiled with four different flags on latest and all pass. Thank you!
