### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by nityanand86876** [cathugger/mkp224o#94]
while compilation i got this error 
```/home/test/.usr/usr/lib/x86_64-linux-gnu//libsodium.so: undefined reference to `getrandom@GLIBC_2.25'
/home/test/.usr/usr/lib/x86_64-linux-gnu//libsodium.so: undefined reference to `getentropy@GLIBC_2.25'
/home/test/.usr/usr/lib/x86_64-linux-gnu//libsodium.so: undefined reference to `__explicit_bzero_chk@GLIBC_2.25'
collect2: error: ld returned 1 exit status
GNUmakefile:99: recipe for target 'mkp224o' failed
make: *** [mkp224o] Error 1```
how to resolve it?

**Comment by nityanand86876** [comment]
here is the full log
[filename.txt](https://github.com/cathugger/mkp224o/files/11112876/filename.txt)

**Comment by nityanand86876** [comment]
or tell me the steps on how to install it without sudo access or root

**Comment by cathugger** [comment]
this looks like an error of libsodium that you have installed in your home folder. did you compile it yourself? where did you get it from? it looks like it's compiled for newer system than you try to use it in.
i think you should be able to compile libsodium yourself and point mkp224o to it (in probably the same way as you have already tried).
or maybe you could find libsodium that is compiled for older glibc, that'd be an option too.
either way linker error happens in finding things your version of libsodium references, not mkp224o.
you could also probably do static compilation of mkp224o if you have the right `libsodium.a` and also static version of libc (possibly in musl system like alpine), but again i'd need to research a bit to give precise instructions for that, i think CFLAGS/LDFLAGS setting of `-static` in the right environment plus `ldd` invocation for confirmation would do. with that you could end up with `mkp224o` binary you could use anywhere.
do some more research on your own tbh as i've been sorta sicky past weeks and not too keen on doing someone else's homework right now. i did have experience with this stuff in past though so i can at least tell you that it's definitely possible.
good luck!
